#!/bin/sh

WAREHOUSES=1
DBMS="pgsql"

if [ $# -ge 1 ]; then
	WAREHOUSES=$1
fi

if [ $# -ge 2 ]; then
	DBMS=$2
fi

CONTAINER_DIR="$(dirname "$0")"

"$CONTAINER_DIR/prepare-image"
"$CONTAINER_DIR/build-database" "$WAREHOUSES" "$DBMS" &
"$CONTAINER_DIR/build-client" &
"$CONTAINER_DIR/build-driver" &
wait
